[Paddle]Add chapter_recurrent-neural-networks
d2l-ai/d2l-zh pull request #1157
Opened 2022-05-31 10:10 UTC by tngt

2022-06-01 03:29 UTC, w5688414 commented
Hi, @AnirudhDagar @cheungdaven chapter recurrent neural networks is ready, can you review this chapter? Thanks

2022-06-14 17:40 UTC, cheungdaven requested changes
please fix the conflicts. Thanks.

2022-06-14 17:40 UTC, cheungdaven commented on chapter_recurrent-neural-networks/rnn-scratch.md
> +    """训练网络一个迭代周期（定义见第8章"""
missing ")"

2022-06-14 17:59 UTC, cheungdaven requested changes

2022-06-14 17:59 UTC, cheungdaven commented on chapter_recurrent-neural-networks/rnn-scratch.md
> +                # `state`对于`nn.LSTM`或对于我们从零开始实现的模型是个张量
remove ``

2022-06-14 18:02 UTC, cheungdaven commented
Also, the 困惑度 of paddle is too high  (in rnn-scratch and rnn-concise).

2022-06-15 09:07 UTC, tngt commented
> Also, the 困惑度 of paddle is too high (in rnn-scratch and rnn-concise).

@w5688414 could you help me evaluate this problem？thanks！！！

2022-06-22 00:11 UTC, merged