[Paddle]Add chapter_attention-mechanisms
d2l-ai/d2l-zh pull request #1160
Opened 2022-06-02 10:06 UTC by tngt

2022-06-22 00:36 UTC, cheungdaven requested changes

2022-06-22 00:36 UTC, cheungdaven commented on chapter_attention-mechanisms/bahdanau-attention.md
> +        # num_hiddens)
don't start new line here.

2022-06-22 00:36 UTC, cheungdaven commented on chapter_attention-mechanisms/nadaraya-waston.md
> +values = paddle.arange(20, dtype='float32').reshape((2,10))
(2, 10)

2022-06-22 00:36 UTC, cheungdaven commented on chapter_attention-mechanisms/nadaraya-waston.md
> +animator = d2l.Animator(xlabel='epoch', ylabel='loss', xlim=[1,5])
[1, 5]

2022-06-22 10:10 UTC, w5688414 commented on chapter_attention-mechanisms/nadaraya-waston.md
> +values = paddle.arange(20, dtype='float32').reshape((2,10))
Done

2022-06-22 10:10 UTC, w5688414 commented on chapter_attention-mechanisms/nadaraya-waston.md
> +animator = d2l.Animator(xlabel='epoch', ylabel='loss', xlim=[1,5])
Done

2022-06-22 10:11 UTC, w5688414 commented on chapter_attention-mechanisms/bahdanau-attention.md
> +        # num_hiddens)
Done

2022-06-22 10:11 UTC, w5688414 commented on chapter_attention-mechanisms/attention-scoring-functions.md
> +    #     # 最后一轴上被掩蔽的元素使用一个非常大的负值替换，从而其softmax输出为0
Done

2022-06-22 18:07 UTC, cheungdaven commented
@w5688414 could you fix the CI issue? It seems that showheatmap function is not in the paddle.py file.

2022-06-23 03:10 UTC, w5688414 commented
> map function is not in the paddle.py file.

I updated the paddle.py, it works fine again, can you review this chapter again?

2022-06-23 18:15 UTC, cheungdaven approved these changes

2022-06-23 18:15 UTC, merged