[Paddle]Add chapter_optimization
d2l-ai/d2l-zh pull request #1165
Opened 2022-06-08 14:21 UTC by tngt

2022-06-24 05:11 UTC, w5688414 commented
chapter chapter_optimization is ready, can you review this chapter? @cheungdaven  thanks

2022-06-28 21:12 UTC, cheungdaven requested changes

2022-06-28 21:12 UTC, cheungdaven commented on chapter_optimization/lr-scheduler.md
> +scheduler =paddle.optimizer.lr.MultiStepDecay(learning_rate = 0.5, milestones = [15,30], gamma=0.5)
learning_rate=0.5, milestones=[15, 30], gamma=0.5

2022-06-28 21:12 UTC, cheungdaven commented on chapter_optimization/lr-scheduler.md
> +trainer = paddle.optimizer.SGD(learning_rate = scheduler, parameters=net.parameters())
learning_rate=scheduler,

2022-06-28 21:12 UTC, cheungdaven commented on chapter_optimization/minibatch-sgd.md
> +    w = d2l.tensor(d2l.normal(mean=0.0, std=0.01, shape=(feature_dim, 1),),stop_gradient=False)
shape=(feature_dim, 1)), stop_gradient=False

2022-06-29 11:09 UTC, w5688414 commented on chapter_optimization/adadelta.md
> +    s_w, s_b = d2l.zeros(shape=(feature_dim, 1)), d2l.zeros(shape=(1,))
Done

2022-06-29 11:09 UTC, w5688414 commented on chapter_optimization/adadelta.md
> +    delta_w, delta_b = d2l.zeros(shape=(feature_dim, 1)), d2l.zeros(shape=(1,))
Done

2022-06-29 11:10 UTC, w5688414 commented on chapter_optimization/adagrad.md
> +    s_b = d2l.zeros(shape=(1,))
Done

2022-06-29 11:11 UTC, w5688414 commented on chapter_optimization/adam.md
> +    v_w, v_b = d2l.zeros((feature_dim, 1)), d2l.zeros((1,))
Done

2022-06-29 11:11 UTC, w5688414 commented on chapter_optimization/adam.md
> +    s_w, s_b = d2l.zeros((feature_dim, 1)), d2l.zeros((1,))
Done

2022-06-29 11:12 UTC, w5688414 commented on chapter_optimization/lr-scheduler.md
> +scheduler =paddle.optimizer.lr.MultiStepDecay(learning_rate = 0.5, milestones = [15,30], gamma=0.5)
Done

2022-06-29 11:12 UTC, w5688414 commented on chapter_optimization/lr-scheduler.md
> +trainer = paddle.optimizer.SGD(learning_rate = scheduler, parameters=net.parameters())
Done

2022-06-29 11:14 UTC, w5688414 commented on chapter_optimization/minibatch-sgd.md
> +    w = d2l.tensor(d2l.normal(mean=0.0, std=0.01, shape=(feature_dim, 1),),stop_gradient=False)
Done

2022-06-29 18:05 UTC, cheungdaven commented
@w5688414 could please fix the CI issues, thanks!

2022-06-30 05:08 UTC, w5688414 commented
> @w5688414 could please fix the CI issues, thanks!

I fixed the missing show_list_len_pair_hist issue, it works fine right now, can you review this chapter again?

2022-06-30 18:27 UTC, merged