[Paddle]Add chapter_computational-performance
d2l-ai/d2l-zh pull request #1167
Opened 2022-06-13 10:39 UTC by tngt

2022-06-17 02:25 UTC, w5688414 commented
![image](https://user-images.githubusercontent.com/12107462/174212380-4eb5f875-0148-4491-9486-7820484778b7.png)

I was wondering why async-computation.md will run on cpu? but the code needs to run on gpu, is configuration right?

2022-06-28 21:14 UTC, cheungdaven commented
> ![image](https://user-images.githubusercontent.com/12107462/174212380-4eb5f875-0148-4491-9486-7820484778b7.png)
> 
> I was wondering why async-computation.md will run on cpu? but the code needs to run on gpu, is configuration right? the program works fine on my local machine
> 
> @[cheungdaven](https://github.com/cheungdaven)

Could you try to put d2l.try_gpu() in th beginning of this notebook? @w5688414

2022-06-28 22:01 UTC, cheungdaven requested changes

2022-06-29 10:40 UTC, w5688414 commented on chapter_computational-performance/async-computation.md
> +:begin_tab:`pytorch`
Done

2022-06-29 10:41 UTC, w5688414 commented on chapter_computational-performance/async-computation.md
> +:begin_tab:`mxnet`
Done

2022-06-29 10:43 UTC, w5688414 commented on chapter_computational-performance/async-computation.md
> +with d2l.Benchmark('不等待计算完成'):
Done

2022-06-29 10:43 UTC, w5688414 commented on chapter_computational-performance/async-computation.md
> +with d2l.Benchmark('同步执行'):
Done

2022-06-29 10:43 UTC, w5688414 commented on chapter_computational-performance/async-computation.md
> +with d2l.Benchmark('异步执行'):
Done

2022-06-29 10:47 UTC, w5688414 commented on chapter_computational-performance/auto-parallelism.md
> +通常情况下单个操作符将使用所有CPU或单个GPU上的所有计算资源。例如，即使在一台机器上有多个CPU处理器，`dot` 操作符也将使用所有CPU上的所有核心（和线程）。这样的行为同样适用于单个GPU。因此，并行化对于单设备计算机来说并不是很有用，而并行化对于多个设备就很重要了。虽然并行化通常应用在多个GPU之间，但增加本地CPU以后还将提高少许性能。例如，`Hadjis.Zhang.Mitlia
Done

2022-06-29 10:53 UTC, w5688414 commented on chapter_computational-performance/hybridize.md
> +# 因为飞桨动态图太快了，需要增加更多的线形图来对比，比如42层。
Done

2022-06-29 11:03 UTC, w5688414 commented on chapter_computational-performance/multiple-gpus.md
> +    xy = int(XY.shape[0]/len(devices)) # 根据GPU数目计算分块大小
Done

2022-06-30 20:32 UTC, cheungdaven commented
@w5688414 could you fix the conflicts? thanks!

2022-07-02 04:13 UTC, w5688414 commented
> @w5688414 could you fix the conflicts? thanks!

the conflicts was fixed, it works fine again, can you review this chapter again? @cheungdaven

2022-07-05 18:34 UTC, merged