[Paddle]Add chapter_computer-vision
d2l-ai/d2l-zh pull request #1173
Opened 2022-06-20 08:48 UTC by tngt

2022-07-05 20:17 UTC, cheungdaven requested changes

2022-07-05 20:17 UTC, cheungdaven commented on chapter_computer-vision/semantic-segmentation-and-dataset.md
> +imgs = [img.transpose([1,2,0]).astype(paddle.uint8) for img in imgs]
[1, 2, 0]

2022-07-05 20:17 UTC, cheungdaven commented
Could you also tune the performance of paddlepaddle in ssd.md.

2022-07-07 12:00 UTC, w5688414 commented on chapter_computer-vision/anchor.md
> +        bbox_mask = paddle.tile(paddle.to_tensor((anchors_bbox_map >= 0), dtype='float32').unsqueeze(-1),(1,4))
Done

2022-07-07 12:02 UTC, w5688414 commented on chapter_computer-vision/fcn.md
> +    return F.cross_entropy(inputs.transpose([0,2,3,1]), targets, reduction='none').mean(1).mean(1)
Done

2022-07-07 12:02 UTC, w5688414 commented on chapter_computer-vision/fcn.md
> +                 test_labels[i], *crop_rect).transpose([1,2,0]).astype("uint8")]
Done

2022-07-07 12:03 UTC, w5688414 commented on chapter_computer-vision/semantic-segmentation-and-dataset.md
> +imgs = [img.transpose([1,2,0]).astype(paddle.uint8) for img in imgs]
Done

2022-07-07 15:51 UTC, w5688414 commented
<img width="699" alt="image" src="https://user-images.githubusercontent.com/12107462/177816711-d6826bf2-15d5-40a1-ad8a-5765d3b2d8aa.png">
 
I fixed the issue and solved the conflicts, re run the ssd section, the result seems ok right now, can you review this chapter again? @cheungdaven thanks

2022-07-07 20:31 UTC, merged